import { NextRequest, NextResponse } from 'next/server';

// GET /api/sites/templates/:id - Get theme defaults for a template
export async function GET(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id: templateId } = await params;

  const themes: Record<string, Record<string, unknown>> = {
    noir: {
      primaryColor: '#000000',
      accentColor: '#ff6347',
      secondaryColor: '#1a1a1a',
      textColor: '#ffffff',
      mutedColor: '#888888',
      fontHeading: 'Playfair Display',
      fontBody: 'Inter',
      darkMode: true,
      borderRadius: '0px',
      heroOverlay: 0.7,
      animations: true,
    },
    vinyl: {
      primaryColor: '#2d1b0e',
      accentColor: '#d4a574',
      secondaryColor: '#4a3728',
      textColor: '#f5e6d3',
      mutedColor: '#a89080',
      fontHeading: 'Bitter',
      fontBody: 'Lora',
      darkMode: true,
      borderRadius: '8px',
      heroOverlay: 0.5,
      animations: true,
    },
    neon: {
      primaryColor: '#0a0a0a',
      accentColor: '#00ffff',
      secondaryColor: '#1a0a2e',
      textColor: '#ffffff',
      mutedColor: '#666666',
      fontHeading: 'Orbitron',
      fontBody: 'Rajdhani',
      darkMode: true,
      borderRadius: '0px',
      heroOverlay: 0.8,
      animations: true,
      glowEffects: true,
    },
    acoustic: {
      primaryColor: '#f5f0e8',
      accentColor: '#8b6914',
      secondaryColor: '#e8dcc8',
      textColor: '#2c2416',
      mutedColor: '#6b5d4a',
      fontHeading: 'Merriweather',
      fontBody: 'Source Serif Pro',
      darkMode: false,
      borderRadius: '12px',
      heroOverlay: 0.3,
      animations: true,
    },
    arena: {
      primaryColor: '#1a1a2e',
      accentColor: '#e94560',
      secondaryColor: '#16213e',
      textColor: '#ffffff',
      mutedColor: '#888888',
      fontHeading: 'Anton',
      fontBody: 'Roboto',
      darkMode: true,
      borderRadius: '4px',
      heroOverlay: 0.6,
      animations: true,
      dramaticEffects: true,
    },
    editorial: {
      primaryColor: '#ffffff',
      accentColor: '#000000',
      secondaryColor: '#f8f8f8',
      textColor: '#1a1a1a',
      mutedColor: '#666666',
      fontHeading: 'Cormorant Garamond',
      fontBody: 'Nunito Sans',
      darkMode: false,
      borderRadius: '0px',
      heroOverlay: 0.2,
      animations: false,
    },
    outlaw: {
      primaryColor: '#1c1610',
      accentColor: '#c9a962',
      secondaryColor: '#2d2520',
      textColor: '#e8dcc8',
      mutedColor: '#8a7a6a',
      fontHeading: 'Oswald',
      fontBody: 'Libre Baskerville',
      darkMode: true,
      borderRadius: '0px',
      heroOverlay: 0.5,
      animations: true,
      textureOverlay: true,
    },
    futura: {
      primaryColor: '#0d0d0d',
      accentColor: '#c0c0c0',
      secondaryColor: '#1a1a1a',
      textColor: '#ffffff',
      mutedColor: '#666666',
      fontHeading: 'Bebas Neue',
      fontBody: 'Montserrat',
      darkMode: true,
      borderRadius: '16px',
      heroOverlay: 0.7,
      animations: true,
      glassmorphism: true,
    },
  };

  const theme = themes[templateId] || themes.noir;

  return NextResponse.json({ theme, templateId });
}
