'use client';

import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { AnimatePresence, motion } from 'framer-motion';
import { Download, FileText, Printer, Copy, Check, X, Music } from '@/components/ui/custom-icons';
import { useState } from 'react';

type SongBlock = {
  id: string;
  type: 'verse' | 'chorus' | 'bridge' | 'pre-chorus' | 'intro' | 'outro' | 'chord';
  content: string;
  chord?: string;
};

type SongExportProps = {
  isOpen: boolean;
  onClose: () => void;
  songTitle: string;
  artist?: string;
  key?: string;
  tempo?: number;
  timeSignature?: string;
  lyrics?: string;
  blocks?: SongBlock[];
  chords?: string[];
};

// PDF Styles for Lead Sheet
const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontSize: 11,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 25,
    borderBottom: '2 solid #333',
    paddingBottom: 15,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#000',
    textAlign: 'center',
  },
  artist: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 15,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 30,
    marginTop: 10,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metaLabel: {
    fontSize: 10,
    color: '#666',
    marginRight: 5,
  },
  metaValue: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#ff6347',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  lyricsText: {
    fontSize: 11,
    lineHeight: 1.8,
    color: '#000',
    whiteSpace: 'pre-wrap',
  },
  chordLine: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#ff6347',
    marginBottom: 2,
    fontFamily: 'Courier',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 50,
    right: 50,
    borderTop: '1 solid #eee',
    paddingTop: 10,
    fontSize: 8,
    color: '#999',
    textAlign: 'center',
  },
  pageNumber: {
    position: 'absolute',
    bottom: 30,
    right: 50,
    fontSize: 10,
    color: '#666',
  },
});

// PDF Document Component
const LeadSheetDocument = ({
  songTitle,
  artist,
  key: songKey,
  tempo,
  timeSignature,
  lyrics,
  blocks,
}: Omit<SongExportProps, 'isOpen' | 'onClose' | 'chords'>) => {
  // Parse lyrics into sections if blocks not provided
  const sections = blocks?.length
    ? blocks
    : lyrics
        ?.split(/\n\n+/)
        .map((section, i) => {
          const lines = section.split('\n');
          const firstLine = lines[0] || '';
          const typeMatch = firstLine.match(/^\[([^\]]+)\]/i);
          return {
            id: `section-${i}`,
            type: typeMatch
              ? (typeMatch[1].toLowerCase().replace(/\s+/g, '-') as SongBlock['type'])
              : ('verse' as const),
            content: typeMatch ? lines.slice(1).join('\n').trim() : section,
          };
        })
        .filter((s) => s.content) || [];

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>{songTitle || 'Untitled Song'}</Text>
          {artist && <Text style={styles.artist}>by {artist}</Text>}
          <View style={styles.metaRow}>
            {songKey && (
              <View style={styles.metaItem}>
                <Text style={styles.metaLabel}>Key:</Text>
                <Text style={styles.metaValue}>{songKey}</Text>
              </View>
            )}
            {tempo && (
              <View style={styles.metaItem}>
                <Text style={styles.metaLabel}>Tempo:</Text>
                <Text style={styles.metaValue}>{tempo} BPM</Text>
              </View>
            )}
            {timeSignature && (
              <View style={styles.metaItem}>
                <Text style={styles.metaLabel}>Time:</Text>
                <Text style={styles.metaValue}>{timeSignature}</Text>
              </View>
            )}
          </View>
        </View>

        {/* Song Sections */}
        {sections.map((section, index) => (
          <View key={section.id || index} style={styles.section}>
            <Text style={styles.sectionTitle}>{section.type.replace(/-/g, ' ').toUpperCase()}</Text>
            {'chord' in section && section.chord ? (
              <Text style={styles.chordLine}>{String(section.chord)}</Text>
            ) : null}
            <Text style={styles.lyricsText}>{section.content}</Text>
          </View>
        ))}

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by Rock N' Roll Basement • {new Date().toLocaleDateString()}
        </Text>
        <Text
          style={styles.pageNumber}
          render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
        />
      </Page>
    </Document>
  );
};

export function SongExport({
  isOpen,
  onClose,
  songTitle,
  artist,
  key: songKey,
  tempo,
  timeSignature,
  lyrics,
  blocks,
  chords,
}: SongExportProps) {
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [exportFormat, setExportFormat] = useState<'pdf' | 'text' | 'chordpro'>('pdf');

  // Generate plain text version
  const generatePlainText = () => {
    let text = `${songTitle || 'Untitled Song'}\n`;
    if (artist) text += `by ${artist}\n`;
    text += '\n';

    if (songKey || tempo || timeSignature) {
      const meta = [];
      if (songKey) meta.push(`Key: ${songKey}`);
      if (tempo) meta.push(`Tempo: ${tempo} BPM`);
      if (timeSignature) meta.push(`Time: ${timeSignature}`);
      text += meta.join(' | ') + '\n\n';
    }

    text += '─'.repeat(40) + '\n\n';

    if (blocks?.length) {
      blocks.forEach((block) => {
        text += `[${block.type.toUpperCase()}]\n`;
        if (block.chord) text += `Chords: ${block.chord}\n`;
        text += block.content + '\n\n';
      });
    } else if (lyrics) {
      text += lyrics;
    }

    text += '\n─'.repeat(40) + '\n';
    text += `Generated by Rock N' Roll Basement • ${new Date().toLocaleDateString()}`;

    return text;
  };

  // Generate ChordPro format
  const generateChordPro = () => {
    let text = `{title: ${songTitle || 'Untitled Song'}}\n`;
    if (artist) text += `{artist: ${artist}}\n`;
    if (songKey) text += `{key: ${songKey}}\n`;
    if (tempo) text += `{tempo: ${tempo}}\n`;
    if (timeSignature) text += `{time: ${timeSignature}}\n`;
    text += '\n';

    if (blocks?.length) {
      blocks.forEach((block) => {
        text += `{comment: ${block.type.toUpperCase()}}\n`;
        text += block.content + '\n\n';
      });
    } else if (lyrics) {
      text += lyrics;
    }

    return text;
  };

  // Download PDF
  const downloadPDF = async () => {
    setGenerating(true);
    try {
      const doc = (
        <LeadSheetDocument
          songTitle={songTitle}
          artist={artist}
          key={songKey}
          tempo={tempo}
          timeSignature={timeSignature}
          lyrics={lyrics}
          blocks={blocks}
        />
      );
      const blob = await pdf(doc).toBlob();
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${(songTitle || 'song').replace(/[^a-z0-9]/gi, '_')}_Lead_Sheet.pdf`;
      link.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('PDF generation error:', error);
    } finally {
      setGenerating(false);
    }
  };

  // Download text file
  const downloadText = (format: 'text' | 'chordpro') => {
    const content = format === 'chordpro' ? generateChordPro() : generatePlainText();
    const ext = format === 'chordpro' ? 'chopro' : 'txt';
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${(songTitle || 'song').replace(/[^a-z0-9]/gi, '_')}.${ext}`;
    link.click();
    URL.revokeObjectURL(url);
  };

  // Copy to clipboard
  const copyToClipboard = async () => {
    const text = generatePlainText();
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Print
  const handlePrint = () => {
    const content = generatePlainText();
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>${songTitle || 'Song'} - Lead Sheet</title>
            <style>
              body { font-family: Georgia, serif; padding: 40px; max-width: 800px; margin: 0 auto; }
              h1 { font-size: 28px; margin-bottom: 5px; }
              .meta { color: #666; margin-bottom: 20px; }
              pre { font-family: inherit; white-space: pre-wrap; line-height: 1.8; }
              .section-title { font-weight: bold; color: #ff6347; text-transform: uppercase; margin-top: 20px; }
            </style>
          </head>
          <body>
            <pre>${content}</pre>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center p-4"
        style={{ backgroundColor: 'rgba(0, 0, 0, 0.5)' }}
        onClick={onClose}
      >
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="w-full max-w-md overflow-hidden rounded-2xl shadow-2xl"
          style={{ background: 'var(--background)', border: '1px solid var(--border)' }}
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div
            className="flex items-center justify-between border-b p-6"
            style={{ borderColor: 'var(--border)' }}
          >
            <div className="flex items-center gap-3">
              <div
                className="flex h-10 w-10 items-center justify-center rounded-xl"
                style={{
                  background:
                    'linear-gradient(135deg, rgba(255, 99, 71, 0.2), rgba(255, 215, 0, 0.1))',
                }}
              >
                <Music className="h-5 w-5" style={{ color: 'var(--accent)' }} />
              </div>
              <div>
                <h2 className="text-lg font-bold" style={{ color: 'var(--text)' }}>
                  Export Song
                </h2>
                <p className="text-sm" style={{ color: 'var(--muted)' }}>
                  Download or share your lead sheet
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="rounded-lg p-2 transition hover:opacity-80"
              style={{ background: 'var(--panel)' }}
            >
              <X className="h-5 w-5" style={{ color: 'var(--muted)' }} />
            </button>
          </div>

          {/* Content */}
          <div className="p-6">
            {/* Format Selection */}
            <div className="mb-6">
              <label className="mb-2 block text-sm font-medium" style={{ color: 'var(--text)' }}>
                Export Format
              </label>
              <div className="flex gap-2">
                {[
                  { id: 'pdf', label: 'PDF', icon: FileText },
                  { id: 'text', label: 'Text', icon: FileText },
                  { id: 'chordpro', label: 'ChordPro', icon: Music },
                ].map((format) => (
                  <button
                    key={format.id}
                    onClick={() => setExportFormat(format.id as typeof exportFormat)}
                    className="flex flex-1 items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-medium transition"
                    style={{
                      background: exportFormat === format.id ? 'var(--accent)' : 'var(--panel)',
                      color: exportFormat === format.id ? 'white' : 'var(--text)',
                      border: `1px solid ${exportFormat === format.id ? 'var(--accent)' : 'var(--border)'}`,
                    }}
                  >
                    <format.icon className="h-4 w-4" />
                    {format.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Preview Info */}
            <div
              className="mb-6 rounded-xl p-4"
              style={{ background: 'var(--panel)', border: '1px solid var(--border)' }}
            >
              <h3 className="mb-2 font-semibold" style={{ color: 'var(--text)' }}>
                {songTitle || 'Untitled Song'}
              </h3>
              <div className="flex flex-wrap gap-3 text-xs" style={{ color: 'var(--muted)' }}>
                {songKey && <span>Key: {songKey}</span>}
                {tempo && <span>Tempo: {tempo} BPM</span>}
                {timeSignature && <span>Time: {timeSignature}</span>}
                {blocks?.length && <span>{blocks.length} sections</span>}
              </div>
            </div>

            {/* Actions */}
            <div className="space-y-3">
              <button
                onClick={() => {
                  if (exportFormat === 'pdf') {
                    downloadPDF();
                  } else {
                    downloadText(exportFormat);
                  }
                }}
                disabled={generating}
                className="flex w-full items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-medium text-white transition disabled:opacity-50"
                style={{ background: 'var(--accent)' }}
              >
                {generating ? (
                  <>
                    <div className="h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Download className="h-4 w-4" />
                    Download {exportFormat.toUpperCase()}
                  </>
                )}
              </button>

              <div className="flex gap-3">
                <button
                  onClick={copyToClipboard}
                  className="flex flex-1 items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-medium transition"
                  style={{ background: 'var(--panel)', color: 'var(--text)' }}
                >
                  {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  {copied ? 'Copied!' : 'Copy'}
                </button>
                <button
                  onClick={handlePrint}
                  className="flex flex-1 items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-medium transition"
                  style={{ background: 'var(--panel)', color: 'var(--text)' }}
                >
                  <Printer className="h-4 w-4" />
                  Print
                </button>
              </div>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
